name: x86-64 Diy Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表
      split_images_size:
        description: '每个文件的大小（MB）'
        required: true
        default: '100'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}-amd64.tar"
        done

    - name: Compress the TAR files
      run: |
        tar -czf x86-64-images.tar.gz *-amd64.tar
        split -b "${{ github.event.inputs.split_images_size }}" --additional-suffix=.tar.gz x86-64-images.tar.gz x86-64-images-part-

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-aa
        path: x86-64-images-part-aa*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ab
        path: x86-64-images-part-ab*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ac
        path: x86-64-images-part-ac*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ad
        path: x86-64-images-part-ad*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ae
        path: x86-64-images-part-ae*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-af
        path: x86-64-images-part-af*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ag
        path: x86-64-images-part-ag*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ah
        path: x86-64-images-part-ah*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-ai
        path: x86-64-images-part-ai*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar-aj
        path: x86-64-images-part-aj*
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
        rm x86-64-images.tar.gz
